// 初始/模板工作区。均为 Blockly XML（加载时兼容），新存档统一保存为 JSON(.m7p)。

// 空白工程：仅一个不可删除的「开始」积木。
export const emptyXml = `<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="start_flow" id="start" x="120" y="100"></block>
</xml>`;

// 单账号模板
export const singleUserXml = `<xml xmlns="https://developers.google.com/blockly/xml"><block type="start_flow" id="start" x="132" y="89"><next><block type="controls_whileUntil"><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="close_gi"><next><block type="close_game"><next><block type="wait_seconds"><field name="TIME_VALUE">10</field><field name="TIME_UNIT">SECONDS</field><next><block type="run_better_gi"><next><block type="close_gi"><next><block type="wait_seconds"><field name="TIME_VALUE">10</field><field name="TIME_UNIT">SECONDS</field><next><block type="daily_mission"><next><block type="refresh_stamina"><next><block type="daily_mission"><next><block type="close_game"><next><block type="wait_seconds"><field name="TIME_VALUE">10</field><field name="TIME_UNIT">SECONDS</field><next><block type="controls_if_else"><value name="IF0"><block type="logic_operation"><field name="OP">OR</field><value name="A"><block type="logic_compare"><field name="OP">LT</field><value name="A"><block type="current_hour_24"></block></value><value name="B"><shadow type="math_number"><field name="NUM">4</field></shadow></value></block></value><value name="B"><block type="logic_compare"><field name="OP">GTE</field><value name="A"><block type="current_hour_24"></block></value><value name="B"><shadow type="math_number"><field name="NUM">17</field></shadow></value></block></value></block></value><statement name="DO0"><block type="wait_until_time"><field name="HOUR">4</field><field name="MINUTE">10</field></block></statement><statement name="ELSE"><block type="wait_seconds"><field name="TIME_VALUE">4</field><field name="TIME_UNIT">HOURS</field></block></statement></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></statement></block></next></block></xml>`;

// 多账号模板
export const multiAccountXml = `<xml xmlns="https://developers.google.com/blockly/xml"><block type="start_flow" id="start" x="133" y="108"><next><block type="custom_function_def" collapsed="true"><field name="FUNC_NAME">星铁刷体力做每日</field><field name="PARAMS">账号</field><statement name="DO"><block type="close_game"><next><block type="wait_seconds"><field name="TIME_VALUE">10</field><field name="TIME_UNIT">SECONDS</field><next><block type="load_account"><value name="ACCOUNT_NAME"><shadow type="text"><field name="TEXT">默认账号</field></shadow><block type="custom_parameter"><field name="PARAM_NAME">账号</field></block></value><next><block type="refresh_stamina"><next><block type="daily_mission"><next><block type="close_game"><next><block type="save_account"><value name="SAVE_NAME"><shadow type="text"><field name="TEXT">默认账号</field></shadow><block type="custom_parameter"><field name="PARAM_NAME">账号</field></block></value><next><block type="wait_seconds"><field name="TIME_VALUE">10</field><field name="TIME_UNIT">SECONDS</field></block></next></block></next></block></next></block></next></block></next></block></next></block></statement><next><block type="custom_function_def" collapsed="true"><field name="FUNC_NAME">原神一条龙</field><field name="PARAMS">账号</field><statement name="DO"><block type="wait_seconds"><field name="TIME_VALUE">10</field><field name="TIME_UNIT">SECONDS</field><next><block type="import_gi_account"><value name="ACCOUNT_NAME"><shadow type="text"><field name="TEXT">默认账号</field></shadow><block type="custom_parameter"><field name="PARAM_NAME">账号</field></block></value><next><block type="run_better_gi"><next><block type="export_gi_account"><value name="ACCOUNT_NAME"><shadow type="text"><field name="TEXT">默认账号</field></shadow><block type="custom_parameter"><field name="PARAM_NAME">账号</field></block></value><next><block type="wait_seconds"><field name="TIME_VALUE">10</field><field name="TIME_UNIT">SECONDS</field></block></next></block></next></block></next></block></next></block></statement><next><block type="controls_whileUntil"><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="custom_function_call"><field name="FUNC_NAME">原神一条龙</field><value name="ARGS"><shadow type="text"><field name="TEXT"></field></shadow><block type="text"><field name="TEXT">account1</field></block></value><next><block type="custom_function_call"><field name="FUNC_NAME">星铁刷体力做每日</field><value name="ARGS"><shadow type="text"><field name="TEXT"></field></shadow><block type="text"><field name="TEXT">account1</field></block></value><next><block type="wait_until_time"><field name="HOUR">4</field><field name="MINUTE">10</field></block></next></block></next></block></statement></block></next></block></next></block></next></block></xml>`;

export const templates = [
  { key: 'empty', name: '空白工程', xml: emptyXml },
  { key: 'single', name: '单账号模板', xml: singleUserXml },
  { key: 'multi', name: '多账号模板', xml: multiAccountXml },
];
