// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AppDataPath():Promise<string>;

export function ClearGiReg():Promise<void>;

export function ClearHsrReg():Promise<void>;

export function ClearWwReg():Promise<void>;

export function ClearZzzReg():Promise<void>;

export function CloseGame():Promise<void>;

export function CloseGi():Promise<void>;

export function CloseZzz():Promise<void>;

export function DailyMission():Promise<void>;

export function EndRun():Promise<void>;

export function Exists(arg1:string):Promise<boolean>;

export function ExportAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportGiAccount(arg1:string):Promise<void>;

export function ExportZzzAccount(arg1:string):Promise<void>;

export function Farming():Promise<void>;

export function FullRun():Promise<void>;

export function GenshinAutoLogin(arg1:string):Promise<void>;

export function GetAccountUID():Promise<number>;

export function GetAutoRunFile():Promise<string>;

export function GetNewVersion():Promise<string>;

export function GetVersion():Promise<string>;

export function ImportGiAccount(arg1:string):Promise<void>;

export function ImportZzzAccount(arg1:string):Promise<void>;

export function Interrupt():Promise<void>;

export function IsRunning():Promise<boolean>;

export function KillOkWw():Promise<void>;

export function ListAccounts():Promise<Array<string>>;

export function ListGiAccounts():Promise<Array<string>>;

export function ListZzzAccounts():Promise<Array<string>>;

export function LoadAccount(arg1:string):Promise<void>;

export function LoadBackendConfig():Promise<config.BackendConfig>;

export function Mkdir(arg1:string):Promise<void>;

export function OpenProjectDialog():Promise<string>;

export function OpenReleasePage():Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RefreshStamina():Promise<void>;

export function RunBetterGi():Promise<void>;

export function RunBetterGiByConfig(arg1:string):Promise<void>;

export function RunBetterGiGui():Promise<void>;

export function RunBetterGiScheduler(arg1:string):Promise<void>;

export function RunCommand(arg1:string):Promise<string>;

export function RunCommandBackground(arg1:string):Promise<string>;

export function RunM7Launcher():Promise<void>;

export function RunZzzod():Promise<void>;

export function RunZzzodGui():Promise<void>;

export function SaveAccount(arg1:string):Promise<void>;

export function SaveBackendConfig(arg1:config.BackendConfig):Promise<void>;

export function SaveProjectDialog():Promise<string>;

export function SimulatedUniverse():Promise<void>;

export function StartOkWwDaily():Promise<void>;

export function StartOkWwWeekly():Promise<void>;

export function StartRun():Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
