// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDataPath() {
  return window['go']['main']['App']['AppDataPath']();
}

export function ClearGiReg() {
  return window['go']['main']['App']['ClearGiReg']();
}

export function ClearHsrReg() {
  return window['go']['main']['App']['ClearHsrReg']();
}

export function ClearWwReg() {
  return window['go']['main']['App']['ClearWwReg']();
}

export function ClearZzzReg() {
  return window['go']['main']['App']['ClearZzzReg']();
}

export function CloseGame() {
  return window['go']['main']['App']['CloseGame']();
}

export function CloseGi() {
  return window['go']['main']['App']['CloseGi']();
}

export function CloseZzz() {
  return window['go']['main']['App']['CloseZzz']();
}

export function DailyMission() {
  return window['go']['main']['App']['DailyMission']();
}

export function EndRun() {
  return window['go']['main']['App']['EndRun']();
}

export function Exists(arg1) {
  return window['go']['main']['App']['Exists'](arg1);
}

export function ExportAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportAccount'](arg1, arg2, arg3);
}

export function ExportGiAccount(arg1) {
  return window['go']['main']['App']['ExportGiAccount'](arg1);
}

export function ExportZzzAccount(arg1) {
  return window['go']['main']['App']['ExportZzzAccount'](arg1);
}

export function Farming() {
  return window['go']['main']['App']['Farming']();
}

export function FullRun() {
  return window['go']['main']['App']['FullRun']();
}

export function GenshinAutoLogin(arg1) {
  return window['go']['main']['App']['GenshinAutoLogin'](arg1);
}

export function GetAccountUID() {
  return window['go']['main']['App']['GetAccountUID']();
}

export function GetAutoRunFile() {
  return window['go']['main']['App']['GetAutoRunFile']();
}

export function GetNewVersion() {
  return window['go']['main']['App']['GetNewVersion']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportGiAccount(arg1) {
  return window['go']['main']['App']['ImportGiAccount'](arg1);
}

export function ImportZzzAccount(arg1) {
  return window['go']['main']['App']['ImportZzzAccount'](arg1);
}

export function Interrupt() {
  return window['go']['main']['App']['Interrupt']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function KillOkWw() {
  return window['go']['main']['App']['KillOkWw']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListGiAccounts() {
  return window['go']['main']['App']['ListGiAccounts']();
}

export function ListZzzAccounts() {
  return window['go']['main']['App']['ListZzzAccounts']();
}

export function LoadAccount(arg1) {
  return window['go']['main']['App']['LoadAccount'](arg1);
}

export function LoadBackendConfig() {
  return window['go']['main']['App']['LoadBackendConfig']();
}

export function Mkdir(arg1) {
  return window['go']['main']['App']['Mkdir'](arg1);
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RefreshStamina() {
  return window['go']['main']['App']['RefreshStamina']();
}

export function RunBetterGi() {
  return window['go']['main']['App']['RunBetterGi']();
}

export function RunBetterGiByConfig(arg1) {
  return window['go']['main']['App']['RunBetterGiByConfig'](arg1);
}

export function RunBetterGiGui() {
  return window['go']['main']['App']['RunBetterGiGui']();
}

export function RunBetterGiScheduler(arg1) {
  return window['go']['main']['App']['RunBetterGiScheduler'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function RunCommandBackground(arg1) {
  return window['go']['main']['App']['RunCommandBackground'](arg1);
}

export function RunM7Launcher() {
  return window['go']['main']['App']['RunM7Launcher']();
}

export function RunZzzod() {
  return window['go']['main']['App']['RunZzzod']();
}

export function RunZzzodGui() {
  return window['go']['main']['App']['RunZzzodGui']();
}

export function SaveAccount(arg1) {
  return window['go']['main']['App']['SaveAccount'](arg1);
}

export function SaveBackendConfig(arg1) {
  return window['go']['main']['App']['SaveBackendConfig'](arg1);
}

export function SaveProjectDialog() {
  return window['go']['main']['App']['SaveProjectDialog']();
}

export function SimulatedUniverse() {
  return window['go']['main']['App']['SimulatedUniverse']();
}

export function StartOkWwDaily() {
  return window['go']['main']['App']['StartOkWwDaily']();
}

export function StartOkWwWeekly() {
  return window['go']['main']['App']['StartOkWwWeekly']();
}

export function StartRun() {
  return window['go']['main']['App']['StartRun']();
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
